# Generated by Django 4.0.4 on 2022-08-22 03:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0002_add_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaalmacen',
            name='ordenCompra_id',
        ),
        migrations.RemoveField(
            model_name='notaalmacen',
            name='pedidoVenta_id',
        ),
        migrations.AddField(
            model_name='notaalmacen',
            name='ordenCompra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventasApp.ordencompra'),
        ),
        migrations.AddField(
            model_name='notaalmacen',
            name='pedidoVenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventasApp.pedidoventa'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 412611)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 412611)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumentoIdentidad',
            field=models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('RUC', 'Registro Único de Contribuyentes'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], default='DNI', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 418597)),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 417598)),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 416600)),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 415604)),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 414606)),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 417598)),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 416600)),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 412611)),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 415604)),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='trabajador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventasApp.trabajador'),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 414606)),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 413613)),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 413613)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 414606)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 411582)),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 21, 22, 55, 57, 411582)),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='usuarioRegistro',
            field=models.CharField(default='admin', max_length=300),
        ),
    ]
