# Generated by Django 4.0.4 on 2022-08-20 06:21

from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from django.db import migrations
def add_group(apps, schema_editor):
    new_group = Group.objects.get_or_create(name='administrador')
    new_group.permissions.add(1)
    new_group.permissions.add(2)
    new_group.permissions.add(3)
    new_group.permissions.add(4)
    new_group.permissions.add(5)
    new_group.permissions.add(6)


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0002_add_user'),
    ]

    operations = [
        migrations.RunPython(add_group),
    ]
