# Generated by Django 4.0.4 on 2022-08-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0002_add_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='usuarioEliminacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='usuarioModificacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
