# Generated by Django 4.0.4 on 2022-08-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0002_add_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categorias',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
