# Generated by Django 4.0.4 on 2022-08-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0003_rename_categoria_producto_categorias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
