# Generated by Django 4.0.4 on 2022-08-22 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0004_alter_categoria_fecharegistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 517851)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 516821)),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='descuentoUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 522843)),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='precioUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='descuentoUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 521843)),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='precioUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='descuentoUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 520844)),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='precioUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='descuentoUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 519814)),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='precioUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='descuentoUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 518817)),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='precioUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 522843)),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 521843)),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 516821)),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='interes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 520844)),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='descuento',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 519814)),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='tasaCambio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='tasaIgv',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='descuento',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 518817)),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='tasaCambio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='tasaIgv',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 517851)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 519814)),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 516821)),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 0, 20, 23, 515875)),
        ),
    ]
