# Generated by Django 4.0.4 on 2022-08-22 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0006_alter_categoria_fecharegistro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 52378)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 52378)),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 58357)),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 57361)),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 56363)),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 55361)),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 54367)),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 57361)),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 57361)),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 52378)),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 56363)),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 55361)),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 53371)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 53371)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 54367)),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 51343)),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 1, 31, 51, 51343)),
        ),
    ]
