# Generated by Django 4.0.4 on 2022-08-27 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0009_alter_categoria_fecharegistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 22727)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 21763)),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 40631)),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 39566)),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 37695)),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 35732)),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 25719)),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 39566)),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 38683)),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 22727)),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Abierta'), (2, 'Cerrada'), (4, 'Anulada')], default=1),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 37695)),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Abierta'), (2, 'Cerrada'), (4, 'Anulada')], default=1),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 26715)),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Abierta'), (2, 'Cerrada'), (4, 'Anulada')], default=1),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 23757)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 23757)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 25719)),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 21763)),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 4, 37, 34, 21763)),
        ),
    ]
