# Generated by Django 4.0.4 on 2022-08-27 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0010_alter_categoria_fecharegistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 602823)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 601826)),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 615788)),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 614791)),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 613793)),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 612796)),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 604818)),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 614791)),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 613793)),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 601826)),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 612796)),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 611799)),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 603820)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 602823)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 604818)),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 601826)),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 5, 15, 41, 600829)),
        ),
    ]
