# Generated by Django 4.0.4 on 2022-08-28 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0014_alter_categoria_fecharegistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 312351)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 311353)),
        ),
        migrations.AlterField(
            model_name='detalledocumentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 324319)),
        ),
        migrations.AlterField(
            model_name='detalledocumentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 323325)),
        ),
        migrations.AlterField(
            model_name='detallenotaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 322324)),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 321294)),
        ),
        migrations.AlterField(
            model_name='detallepedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 313348)),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 324319)),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 323325)),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 311353)),
        ),
        migrations.AlterField(
            model_name='notaalmacen',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 322324)),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 321294)),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 313348)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 312351)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 314346)),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 311353)),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 19, 2, 34, 310321)),
        ),
    ]
